name: darango
version: 0.0.2
author: "Bastien FERBU <bastien.ferbu@gmail.com>"
homepage: https://github.com/BastienFerbu/darango
description: An ArangoDB API for dart

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  http: ^0.12.0+2

dev_dependencies: