name: darango
version: 0.1.1
homepage: https://github.com/BastienFerbu/darango
description: A Dart driver for ArangoDB. It use the ArangoDB HTTP REST API.

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  pedantic: ^1.9.0
